name: Python CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff check (ignore E501)
        run: ruff check --ignore E501 .

      - name: Byte-compile all Python files
        run: python -m compileall .

      - name: Run pytest if tests/ exists
        shell: bash
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo "No tests/ directory. Skipping pytest."
          fi


